[project]
name = "fin-rag-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "akshare>=1.18.94",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "jieba>=0.42.1",
    "langgraph>=1.2.11",
    "numpy>=2.4.6",
    "openai>=3.13.0",
    "pandas>=3.0.5",
    "pdfplumber>=0.11.10",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "rank-bm25>=0.2.2",
    "requests>=2.34.2",
    "uvicorn>=0.53.0",
]
